# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e6381f9d8c38220490728e1525af26b4aff34f6445c510482d1e73a1523efe2cf274f714a19ef2c17bc34a36071d39421db82e328929343b26adb5f57b442e7

test:
  secret_key_base: f311f5502f5a9a3db381c96ca608430281b963c8a1bac57c277b94b02197e8fbe49d0fa4fd1adfc0b80883b870761a7748663fff3f82bddc34531973112e2ec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
